typography_spectrum: 0.6116445744410157
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.9649330235552043
  lightness: 0.6766574187204242
  saturation: 0.28301074425689876
  rhythmicContrast: 0.761994918808341
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.786987938452512
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: John Scott
  email: JScott@academyart.edu
  url: johnscottstories.com
name: RESET
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: John Scott Stories
    url: johnscottstories.com
    type: external
favicon: null
title: NOBODY CAN DO WHAT YOU DO
description: ...like you do it.
purpose: []
