name: RESET
favicon: null
layout_spectrum: 0.99101
typography_spectrum: 0.43521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
